### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by juunr95** [haekb/LithFix#1]
Please, can you help me ?
I'm working on a game with lithtech, and seen that you have more knowledge than me, so,you know if there is some limitation for vertices count ? Cause we got new models, but they dont render correctly. They loads fines and dont report any error, but don't render.

can you help me ?

**Comment by haekb** [comment]
Apologies for not seeing this earlier! 

I do not know the verticies limit. You could try to set `DebugLevel` to something greater than 0 and then attach a debug console to it (If it doesn't have an accessible console.) WinDbg as an example.
